use_frameworks!

target 'SYPopupController_Example' do
    
  pod 'SYPopupController'
  pod 'HexColors', '~>4.0.0'
  pod 'FRHyperLabel'
  
  target 'SYPopupController_Tests' do
    inherit! :search_paths

    
  end
end
